# Generated by Django 4.0.4 on 2022-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_password_user_roll_no_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.CharField(choices=[('Aerospace', 'Aerospace'), ('Mechanical', 'Mechanical')], default='Aerospace', max_length=20),
        ),
    ]
