# Generated by Django 4.0.4 on 2022-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media_choice',
            field=models.CharField(choices=[('1', 'Magazine'), ('2', 'Radio Station'), ('3', 'Journal'), ('4', 'TV Station'), ('5', 'Newspaper'), ('6', 'Website')], default='Website', max_length=25),
        ),
    ]
