# Generated by Django 4.0.4 on 2022-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_user_media_choice_user_is_webd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(default=False),
        ),
    ]
