# Generated by Django 4.0.4 on 2022-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_user_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gd',
            field=models.BooleanField(default=False, verbose_name='Graphic Designer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ma',
            field=models.BooleanField(default=False, verbose_name='Marketting'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ui',
            field=models.BooleanField(default=False, verbose_name='UI/UX Designer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ve',
            field=models.BooleanField(default=False, verbose_name='Video Editor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.TextField(default='Motivation for Joinig Hyperloop Team', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departments',
            field=models.CharField(choices=[('Aerospace', 'Aerospace'), ('Mechanical', 'Mechanical'), ('Chemical', 'Chemical'), ('MEMS', 'MEMS'), ('CS', 'CS'), ('EE', 'EE'), ('EP', 'EP'), ('Civil', 'Civil'), ('ESE', 'ESE')], default='Aerospace', max_length=20),
        ),
    ]
